"""LLM-as-judge evaluation per arXiv 2502.02028, using a local Ollama model.

The paper used Qwen2.5-1.5B/7B to score generations 1-5 on six dimensions;
this runs the same rubric against qwen2.5:7b on the local Ollama instance.
Reads the generations.jsonl produced by evaluate.py.

Usage (from repo root; only needs requests, runs in either venv):
    python -m training.reproduce_paper.llm_judge \\
        --generations training/runs/smollm-135m-full/eval/generations.jsonl
"""

import argparse
import json
import os
from pathlib import Path

import requests
from tqdm import tqdm

REPO_ROOT = Path(__file__).resolve().parents[2]

DIMENSIONS = ["clarity", "completeness", "consistency", "practicality", "relevance", "allergen_safety"]

JUDGE_PROMPT = """You are evaluating a recipe generated by a language model.

Recipe name: {name}
Available ingredients: {ingredients}

Generated cooking instructions:
{generated}

Rate the generated instructions on each dimension from 1 (very poor) to 5 (excellent):
- clarity: are the steps easy to follow and unambiguous?
- completeness: do the instructions cover the full preparation, start to finish?
- consistency: are the steps internally consistent (no contradictions, correct order)?
- practicality: could a home cook realistically execute this?
- relevance: do the instructions match the recipe name and use the listed ingredients?
- allergen_safety: are common allergens in the ingredients handled/flagged appropriately?

Respond with ONLY a JSON object mapping each dimension name to an integer score, e.g.
{{"clarity": 4, "completeness": 3, "consistency": 4, "practicality": 4, "relevance": 5, "allergen_safety": 3}}"""


def resolve(path: str | Path) -> Path:
    path = Path(path)
    return path if path.is_absolute() else REPO_ROOT / path


def judge_one(base_url: str, model: str, gen: dict, timeout: int) -> dict | None:
    prompt = JUDGE_PROMPT.format(
        name=gen["name"],
        ingredients="; ".join(gen["ingredients"]),
        generated=gen["generated"] or "(empty generation)",
    )
    response = requests.post(
        f"{base_url}/api/chat",
        json={
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "format": "json",
            "stream": False,
            "options": {"temperature": 0},
        },
        timeout=timeout,
    )
    response.raise_for_status()
    try:
        scores = json.loads(response.json()["message"]["content"])
    except (json.JSONDecodeError, KeyError):
        return None
    if not all(dim in scores and isinstance(scores[dim], (int, float)) for dim in DIMENSIONS):
        return None
    return {dim: max(1, min(5, int(scores[dim]))) for dim in DIMENSIONS}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--generations", required=True, help="generations.jsonl from evaluate.py")
    parser.add_argument("--model", default="qwen2.5:7b")
    parser.add_argument("--base-url", default=os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434"))
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--timeout", type=int, default=120)
    args = parser.parse_args()

    gen_path = resolve(args.generations)
    with open(gen_path, encoding="utf-8") as f:
        generations = [json.loads(line) for line in f]
    if args.limit:
        generations = generations[: args.limit]

    judged, failures = [], 0
    for gen in tqdm(generations, desc="judging"):
        scores = judge_one(args.base_url, args.model, gen, args.timeout)
        if scores is None:
            failures += 1
            continue
        judged.append({"name": gen["name"], "scores": scores})

    if not judged:
        raise SystemExit(f"All {len(generations)} judge calls failed — is {args.model} "
                         f"available at {args.base_url}?")

    summary = {
        "judge_model": args.model,
        "num_judged": len(judged),
        "num_failed": failures,
        "mean_scores": {
            dim: sum(j["scores"][dim] for j in judged) / len(judged) for dim in DIMENSIONS
        },
    }
    summary["overall_mean"] = sum(summary["mean_scores"].values()) / len(DIMENSIONS)

    output_dir = gen_path.parent
    with open(output_dir / "judged.jsonl", "w", encoding="utf-8") as f:
        for j in judged:
            f.write(json.dumps(j, ensure_ascii=False) + "\n")
    with open(output_dir / "judge_scores.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
